### ISSUE TITLE
bson buffer overflow

### ISSUE THREAD

**Issue by noam-almog** [allegro/node-worker-nodes#10]
Hi,
Right now this library is using bson from mongo. there is a problem with the library [here](https://github.com/mongodb/js-bson/blob/1.0-branch/lib/bson/bson.js#L30).
Bson is using a predefined buffer with max size of 17mb, once this buffer is over node will shut down the process for security reasons without any way for the system to recover from it (no process events, try catch or anything else i could think of).
There aren't many ways to resolve this, bson does not allow us to modify the buffer value which leaves us with two basic options:
1. switch bson with something else, [MessagePack](http://msgpack.org) can be a viable option (and a simple drop in replacement)
2. leave things the way they are but allow to customize the message serializer (leaving the door open for many other binary serializers, like protobuf).

**Comment by kwiatkk1** [comment]
Hi Noam,

thanks for your research and the code! :)
BSON was originally picked because it is binary and schema-less. Replacing it with MessagePack sounds good to me, as it can also be used in a schema-less manner that allows passing arbitrary messages. So I'm for option 1.

I will check in the evening if everything works fine after the switch and I will merge your pull-request then. Thanks!
